import PDFDocument from "pdfkit";

type InvoicePdfInput = {
  invoiceNumber: string;
  issuedAt: Date;
  hotelName: string;
  hotelCity?: string | null;
  hotelCountry?: string | null;
  guestName: string;
  guestPhone: string;
  bookingId: string;
  bookingStatus: string;
  paymentStatus: string;
  roomType: string;
  selectedUnit?: string | null;
  propertyName: string;
  checkIn: Date;
  checkOut: Date;
  nights: number;
  adults: number;
  children: number;
  totalAmount: number;
  currency: string;
};

function formatDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}

function formatMoney(amount: number, currency: string): string {
  return new Intl.NumberFormat("en", { style: "currency", currency, maximumFractionDigits: 2 }).format(amount);
}

export async function buildBookingInvoicePdf(input: InvoicePdfInput): Promise<Buffer> {
  const doc = new PDFDocument({ margin: 44, size: "A4" });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));

  const row = (label: string, value: string): void => {
    doc.font("Helvetica-Bold").fontSize(11).text(`${label}:`, { continued: true });
    doc.font("Helvetica").fontSize(11).text(` ${value}`);
  };

  doc.font("Helvetica-Bold").fontSize(20).text("ChatAstay Invoice / Confirmation", { align: "left" });
  doc.moveDown(0.4);
  doc.font("Helvetica").fontSize(10).text(`Invoice #: ${input.invoiceNumber}`);
  doc.text(`Issued: ${formatDate(input.issuedAt)}`);
  doc.moveDown(0.4);

  doc.font("Helvetica-Bold").fontSize(13).text(input.hotelName);
  doc.font("Helvetica")
    .fontSize(10)
    .text([input.hotelCity, input.hotelCountry].filter(Boolean).join(", ") || "Oman");
  doc.moveDown(0.8);

  doc.font("Helvetica-Bold").fontSize(12).text("Guest Details");
  row("Guest", input.guestName);
  row("Phone", input.guestPhone);
  doc.moveDown(0.7);

  doc.font("Helvetica-Bold").fontSize(12).text("Booking Details");
  row("Booking ID", input.bookingId);
  row("Property", input.propertyName);
  row("Room Type", input.roomType);
  row("Room Unit", input.selectedUnit ?? "Not assigned");
  row("Stay", `${formatDate(input.checkIn)} to ${formatDate(input.checkOut)} (${input.nights} nights)`);
  row("Occupancy", `${input.adults} adults, ${input.children} children`);
  row("Booking Status", input.bookingStatus);
  row("Payment Status", input.paymentStatus);
  row("Total", `${formatMoney(input.totalAmount, input.currency)} (${input.currency})`);
  doc.moveDown(0.8);

  doc.font("Helvetica-Bold").fontSize(12).text("Confirmation Note");
  doc
    .font("Helvetica")
    .fontSize(10)
    .text(
      "This document confirms the reservation details and reflects the latest payment status at the time of issue. " +
        "If payment status changes, the hotel may resend an updated invoice.",
      { align: "left" }
    );

  doc.moveDown(1);
  doc.font("Helvetica").fontSize(9).fillColor("#666").text("Generated by ChatAstay Admin");

  return await new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    doc.end();
  });
}
